### ISSUE TITLE
Get rid of plot warning/error in shuffle_correlations

### ISSUE THREAD

**Issue by dylanfesta** [grawoods/teamA-grebes-NMA2020#6]
[At the end of file  shuffle_correlations.ipynb ](https://github.com/grawoods/teamA-grebes-NMA2020/blob/739d4c6d3369c1375530a5628a1b6b23f131ba8a/shuffle_correlations.ipynb#L234-L243)  the `log10` acts sometimes on bins of zero size, and complaints ensue. I think it's cleaner to explicitly assign `NaN` to those values, so the log10 will result in `NaN` and the plot function will ignore them.  

Simply add the following code before `plt.figure(...` 

```python
hist = hist.astype(float)
hist[hist==0] = np.nan
hist_2 =hist_2.astype(float)
hist_2[hist_2==0] = np.nan
```  
Or, if you feel "functional" ... 
```python
def histnan(x): xx=x.astype(float) ; xx[xx==0]=np.nan ; return xx 
hist = histnan(hist)
hist_2 =  histnan(hist_2)
```

**Comment by ryanharvey1** [comment]
Thanks Dylan. I'll apply those changes in the next couple days.
